### ISSUE TITLE
syntax error in %gato dojo

### ISSUE THREAD

**Issue by vcavallo** [tloncorp/arigato#2]
Hi. I'm noticing the following error in dojo. I can't trace it to any exact behaviors - seems to happen when idling navigating around Groups in the browser (or perhaps its just random/on a timer and i'm attributing causality to the Groups browsing?)

/prompt and /image do work fine for me.

```
error in %gato
%fact
! take %fact failed, closing subscription
! syntax error
! {1 1}
! /app/gato/hoon:<[38 30].[38 68]>
! /app/gato/hoon:<[38 3].[39 28]>
! /app/gato/hoon:<[28 3].[39 28]>
! /app/gato/hoon:<[26 3].[39 28]>
! /app/gato/hoon:<[134 42].[134 59]>
! /app/gato/hoon:<[134 15].[137 63]>
! /app/gato/hoon:<[132 15].[137 63]>
! /app/gato/hoon:<[130 13].[138 15]>
! /app/gato/hoon:<[129 13].[138 15]>
! /app/gato/hoon:<[127 11].[139 13]>
! /app/gato/hoon:<[126 11].[139 13]>
! /app/gato/hoon:<[125 11].[139 13]>
! /app/gato/hoon:<[124 11].[139 13]>
! /app/gato/hoon:<[122 9].[140 11]>
! /app/gato/hoon:<[115 5].[141 7]>
! /app/gato/hoon:<[113 3].[142 5]>
! /app/gato/hoon:<[112 3].[142 5]>
! /sys/vane/gall/hoon:<[1.339 36].[1.339 76]>
```

When I initially poked my API key, I fumbled the paste into the dojo and pasted a malformed poke. If I remember correctly, that's the first time I saw a {1 1} syntax error - but I'm not sure if it's related.

Let me know if you need anything else from me! :gato +dbug is unexciting; just two items from the only two /prompt and /image commands i've run so far.

**Comment by vcavallo** [comment]
Update: does seem to be random/timer-based. I saw it in dojo while I wasn't doing anything in any urbit UI.

**Comment by midsum-salrux** [comment]
You can ignore this output. It will post that on every non-prompt chat message because it's trying and failing to parse it as a prompt.
